---
title: "Mini-Project 4"
author: "Olivia Baldwin"
date: "4/24/2018"
output:
  html_document:
    code_folding: hide
    df_print: paged
---

```{r message = FALSE, echo = FALSE}
library(tidyverse)
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")

```

```{r message = FALSE, echo = FALSE}
query1 <- "SELECT t.title, t.production_year, mi.info, cn.name
FROM movie_info mi
LEFT JOIN title t ON mi.movie_id = t.id
LEFT JOIN movie_companies mc ON mi.id = mc.movie_id
LEFT JOIN company_name cn ON t.phonetic_code = cn.name_pcode_sf
WHERE kind_id = 1
AND company_type_id = 2
AND production_year >= 2000
GROUP BY cn.name
LIMIT 20;"
db %>%
  dbGetQuery(query1)
# language table
query3 <- "SELECT t.id, t.title, mi.info AS lang, t.production_year AS production_year, cn.name AS production_company_name
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
LEFT JOIN movie_companies mc ON mi.id = mc.movie_id
LEFT JOIN company_name cn ON t.phonetic_code = cn.name_pcode_sf
WHERE mi.info_type_id = 4 AND mi.info LIKE '%English%'
AND kind_id = 1
#AND company.type_id = 2
AND production_year >= 2000
GROUP BY cn.name
LIMIT 100;"
lang_table <- db %>%
  dbGetQuery(query3)
lang_table

# movie's name, gross, director, gender of director, and its production company but limited by the year
query2 <- "SELECT t.title, t.id, mi.info AS movie_gross, n.name AS director, n.gender, co.name AS production_company
FROM cast_info ci
LEFT JOIN title t ON ci.movie_id = t.id
LEFT JOIN char_name cn ON cn.id = ci.person_role_id
LEFT JOIN name n ON n.id = ci.person_id
LEFT JOIN movie_info mi ON t.id = mi.movie_id
LEFT JOIN movie_companies mc ON mi.id = mc.movie_id
LEFT JOIN company_name co ON t.phonetic_code = co.name_pcode_sf
WHERE t.kind_id = 1
AND ci.role_id = 8
AND company_type_id = 2
AND info_type_id = 107
AND production_year >= 2000
AND mi.info LIKE '%Worldwide%' OR '%USA%'
GROUP BY ci.person_id;"
# save tablhe
director_gender_prod_comp <- db %>%
  dbGetQuery(query2)
# parse gross
 director_gender_prod_comp <- director_gender_prod_comp %>%
  filter(!is.na(gender)) %>%
  mutate(gross = parse_number(movie_gross))
 director_gender_prod_comp

# tab1 <- left_join(lang_table, select(director_gender_prod_comp, id, title, movie_gross, director, gender), by = 'id')
# 
# tab2 <- left_join(lang_table, select(director_gender_prod_comp, id, movie_gross, director, gender), by = 'id')

table_plot <- director_gender_prod_comp %>%
  mutate(is_femme = ifelse(gender == "f", 1, 0)) %>%
  group_by(production_company) %>%
  summarize(num_f = sum(is_femme),
            num_directors = count(!is.na(director)),
            sum_gross = sum(gross),
            percent_f_director = num_f/num_directors) %>%
  filter(sum_gross >= 300000000) %>%
  filter(!is.na(production_company)) %>%
  arrange(desc(percent_f_director))
table_plot

table_plot %>%
  ggplot(aes(x = reorder(production_company,-sum_gross), y = sum_gross, fill = percent_f_director)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_fill_gradient(high = "#032c6d", low = "#89b6ff",
                      breaks = c(0.00, 0.33, 0.66, 1.00),
                      labels = c("0%", "33.3%", "66.7%", "100%")) +
  theme(axis.text.x = element_blank()) +
  labs(title = "Total Gross of Production Companies vs Gender Disparity of Directors",
       x = "Production Companies",
       y = "Total Gross, 2000-2018 ($)",
       fill = "Percent of\nFemale Directors",
       caption = "Source: Internet Movie Database") +
  scale_y_continuous(breaks = c(0e+00, 2e+09, 4e+09, 6e+09, 8e+09),
                     labels = c("0", "2 billion", "4 billion", "6 billion", "8 billion"))
```

